"""
Export helpers:
  - export_csv     → returns bytes for st.download_button
  - export_pdf     → generates a clean, styled PDF deal memo
"""

import io
from datetime import datetime
from typing import Optional

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas as rl_canvas


# ── Palette ─────────────────────────────────────────────────────────── #
INK         = colors.HexColor("#0F0E1A")
VIOLET      = colors.HexColor("#7B3FE4")
VIOLET_LITE = colors.HexColor("#EDE5FF")
PINK        = colors.HexColor("#D94F82")
TEAL        = colors.HexColor("#00B89C")
TEAL_LITE   = colors.HexColor("#E0F7F4")
GOLD        = colors.HexColor("#C9860A")
GOLD_LITE   = colors.HexColor("#FFF4DC")
MUTED       = colors.HexColor("#6B6690")
RULE        = colors.HexColor("#DDD8F0")
ROW_ALT     = colors.HexColor("#F8F6FF")
WHITE       = colors.white


# ── CSV ──────────────────────────────────────────────────────────────── #

def export_csv(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")


# ── Helpers ──────────────────────────────────────────────────────────── #

def _clean(val, max_len: int = 120) -> str:
    """Safely convert a value to a display string."""
    if pd.isna(val) or val is None:
        return "—"
    s = str(val).strip()
    # Drop strings that look like article headlines (contain verbs / long sentences)
    if len(s) > max_len:
        s = s[:max_len].rstrip() + "…"
    return s or "—"


def _stage_color(stage: str):
    stage = str(stage)
    if stage in ("Pre-Seed", "Seed"):
        return TEAL, TEAL_LITE
    if stage == "Series A":
        return VIOLET, VIOLET_LITE
    if stage in ("Series B", "Series C+", "Growth"):
        return GOLD, GOLD_LITE
    return MUTED, colors.HexColor("#F4F4F4")


# ── Page template with header/footer ─────────────────────────────────── #

class _PageTemplate:
    def __init__(self, fund_name: str, industry: str, date_str: str):
        self.fund_name = fund_name
        self.industry = industry
        self.date_str = date_str

    def __call__(self, canvas, doc):
        canvas.saveState()
        W, H = letter

        # Top accent bar
        canvas.setFillColor(VIOLET)
        canvas.rect(0, H - 0.28 * inch, W, 0.28 * inch, fill=1, stroke=0)

        # Header text on bar
        canvas.setFillColor(WHITE)
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(0.5 * inch, H - 0.19 * inch, "DEAL FLOW MEMO")
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(W - 0.5 * inch, H - 0.19 * inch,
                               f"{self.fund_name}  ·  {self.industry}")

        # Footer rule
        canvas.setStrokeColor(RULE)
        canvas.setLineWidth(0.5)
        canvas.line(0.5 * inch, 0.45 * inch, W - 0.5 * inch, 0.45 * inch)

        # Footer text
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawString(0.5 * inch, 0.28 * inch,
                          f"Generated by What's New  ·  {self.date_str}  ·  Confidential")
        canvas.drawRightString(W - 0.5 * inch, 0.28 * inch,
                               f"Page {doc.page}")

        canvas.restoreState()


# ── Main PDF export ───────────────────────────────────────────────────── #

def export_pdf(
    df: pd.DataFrame,
    industry: str,
    fund_name: str = "Your Fund",
    analyst_name: str = "",
) -> bytes:
    """Render a polished deal-flow PDF memo."""

    buf = io.BytesIO()
    date_str = datetime.today().strftime("%B %d, %Y")

    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.65 * inch,
    )

    page_cb = _PageTemplate(fund_name, industry, date_str)

    # ── Styles ── #
    title_style = ParagraphStyle(
        "MemoTitle",
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=INK,
        spaceAfter=3,
        leading=26,
    )
    sub_style = ParagraphStyle(
        "MemoSub",
        fontName="Helvetica",
        fontSize=10,
        textColor=MUTED,
        spaceAfter=14,
    )
    section_style = ParagraphStyle(
        "Section",
        fontName="Helvetica-Bold",
        fontSize=11,
        textColor=VIOLET,
        spaceBefore=18,
        spaceAfter=8,
        borderPad=0,
    )
    body_style = ParagraphStyle(
        "Body",
        fontName="Helvetica",
        fontSize=8.5,
        textColor=INK,
        leading=13,
        spaceAfter=4,
    )
    card_name_style = ParagraphStyle(
        "CardName",
        fontName="Helvetica-Bold",
        fontSize=9.5,
        textColor=INK,
        leading=13,
        spaceAfter=2,
    )
    card_meta_style = ParagraphStyle(
        "CardMeta",
        fontName="Helvetica",
        fontSize=8,
        textColor=MUTED,
        leading=12,
    )

    story = []

    # ── Title block ── #
    byline = fund_name
    if analyst_name:
        byline += f"  ·  {analyst_name}"
    byline += f"  ·  {date_str}"

    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(f"Deal Flow Memo — {industry}", title_style))
    story.append(Paragraph(byline, sub_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=VIOLET, spaceAfter=10))

    # ── KPIs row ── #
    total = len(df)
    early = len(df[df.get("funding_stage", pd.Series(dtype=str)).isin(["Pre-Seed", "Seed"])]) if "funding_stage" in df.columns else "—"
    trending = len(df[df.get("trend", pd.Series(dtype=str)) != ""]) if "trend" in df.columns else "—"
    avg_score = f"{df['score'].mean():.1f}" if "score" in df.columns and not df.empty else "—"

    kpi_data = [
        [Paragraph(f"<b>{total}</b>", ParagraphStyle("kv", fontName="Helvetica-Bold", fontSize=18, textColor=VIOLET, leading=22)),
         Paragraph(f"<b>{early}</b>", ParagraphStyle("kv2", fontName="Helvetica-Bold", fontSize=18, textColor=TEAL, leading=22)),
         Paragraph(f"<b>{trending}</b>", ParagraphStyle("kv3", fontName="Helvetica-Bold", fontSize=18, textColor=PINK, leading=22)),
         Paragraph(f"<b>{avg_score}</b>", ParagraphStyle("kv4", fontName="Helvetica-Bold", fontSize=18, textColor=GOLD, leading=22))],
        [Paragraph("Total Companies", ParagraphStyle("kl", fontName="Helvetica", fontSize=7.5, textColor=MUTED)),
         Paragraph("Seed or Earlier", ParagraphStyle("kl2", fontName="Helvetica", fontSize=7.5, textColor=MUTED)),
         Paragraph("With Trend Signal", ParagraphStyle("kl3", fontName="Helvetica", fontSize=7.5, textColor=MUTED)),
         Paragraph("Avg Score", ParagraphStyle("kl4", fontName="Helvetica", fontSize=7.5, textColor=MUTED))],
    ]
    W = letter[0] - 1.1 * inch
    kpi_tbl = Table(kpi_data, colWidths=[W/4]*4)
    kpi_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8F6FF")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F8F6FF")]),
        ("BOX", (0, 0), (-1, -1), 0.5, RULE),
        ("LINEAFTER", (0, 0), (2, -1), 0.5, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    story.append(kpi_tbl)

    # ── Top 10 table ── #
    story.append(Paragraph("Top Companies This Week", section_style))

    display_cols = ["name", "funding_stage", "trend", "score"]
    available = [c for c in display_cols if c in df.columns]
    top = (df.nlargest(10, "score") if "score" in df.columns else df.head(10))[available].reset_index(drop=True)

    col_labels = {"name": "Company", "funding_stage": "Stage", "trend": "Trend Signal", "score": "Score"}
    header_row = ["#"] + [col_labels.get(c, c) for c in available]

    tbl_data = [header_row]
    for i, (_, row) in enumerate(top.iterrows()):
        cells = [str(i + 1)]
        for c in available:
            v = row.get(c, "")
            if c == "trend":
                # Truncate trend to first 2 themes
                themes = [t.strip() for t in str(v).split(",") if t.strip()]
                cells.append(", ".join(themes[:2]) + ("…" if len(themes) > 2 else "") if themes else "—")
            elif c == "name":
                cells.append(_clean(v, 45))
            else:
                cells.append(_clean(v, 60))
        tbl_data.append(cells)

    col_w = [0.25*inch, 1.6*inch, 0.75*inch, 2.55*inch, 0.45*inch]
    col_w = col_w[:len(header_row)]

    tbl = Table(tbl_data, colWidths=col_w, repeatRows=1)
    tbl_style = [
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), VIOLET),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 7),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 7),
        ("LEFTPADDING", (0, 0), (-1, 0), 8),
        # Body rows
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ROW_ALT]),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("LEFTPADDING", (0, 1), (-1, -1), 8),
        ("TEXTCOLOR", (0, 1), (-1, -1), INK),
        # Grid
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, RULE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        # Rank col center
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (-1, 0), (-1, -1), "CENTER"),
        # Score col color
        ("TEXTCOLOR", (-1, 1), (-1, -1), VIOLET),
        ("FONTNAME", (-1, 1), (-1, -1), "Helvetica-Bold"),
    ]
    tbl.setStyle(TableStyle(tbl_style))
    story.append(tbl)

    # ── Seed Stage Spotlight as cards ── #
    if "funding_stage" in df.columns:
        seed_df = df[df["funding_stage"].isin(["Pre-Seed", "Seed"])].head(6)
        if not seed_df.empty:
            story.append(Paragraph("Seed Stage Spotlight", section_style))
            story.append(HRFlowable(width="100%", thickness=0.5, color=RULE, spaceAfter=8))

            for _, row in seed_df.iterrows():
                name = _clean(row.get("name", ""), 60)
                stage = str(row.get("funding_stage", ""))
                trend = row.get("trend", "")
                rationale = row.get("rationale", "")
                score = row.get("score", "")

                trend_str = ", ".join([t.strip() for t in str(trend).split(",") if t.strip()][:3]) if trend else ""
                sc, sc_lite = _stage_color(stage)

                # Stage pill + name row
                badge = Table(
                    [[Paragraph(stage, ParagraphStyle("badge", fontName="Helvetica-Bold",
                                                       fontSize=7, textColor=sc, leading=9))]],
                    colWidths=[0.7 * inch]
                )
                badge.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), sc_lite),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("BOX", (0, 0), (-1, -1), 0.5, sc),
                    ("ROUNDEDCORNERS", [4, 4, 4, 4]),
                ]))

                score_txt = f"Score: {_clean(score, 10)}"
                name_para = Paragraph(name, card_name_style)
                meta_parts = []
                if trend_str:
                    meta_parts.append(trend_str)
                if rationale and str(rationale) not in ("—", "No signal detected"):
                    meta_parts.append(_clean(rationale, 100))
                meta_para = Paragraph("  ·  ".join(meta_parts) if meta_parts else "", card_meta_style)

                card_inner = Table(
                    [[badge, name_para, Paragraph(score_txt,
                        ParagraphStyle("sc", fontName="Helvetica-Bold", fontSize=8.5,
                                       textColor=VIOLET, leading=12))]],
                    colWidths=[0.8 * inch, 4.5 * inch, 0.8 * inch],
                )
                card_inner.setStyle(TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ]))

                card = Table(
                    [[card_inner], [meta_para]],
                    colWidths=[letter[0] - 1.1 * inch],
                )
                card.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), WHITE),
                    ("BOX", (0, 0), (-1, -1), 0.5, RULE),
                    ("LINEBELOW", (0, 0), (-1, 0), 0.4, RULE),
                    ("LEFTPADDING", (0, 0), (-1, -1), 12),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                    ("TOPPADDING", (0, 0), (0, 0), 9),
                    ("BOTTOMPADDING", (0, 0), (0, 0), 9),
                    ("TOPPADDING", (0, 1), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
                    ("ROUNDEDCORNERS", [6, 6, 6, 6]),
                ]))

                story.append(KeepTogether([card, Spacer(1, 6)]))

    doc.build(story, onFirstPage=page_cb, onLaterPages=page_cb)
    return buf.getvalue()